spring.application.name=url_sortner_app

spring.profiles.active=dev

spring.datasource.url = jdbc:postgresql://localhost:5432/db_name

spring.datasource.username = username
spring.datasource.password = password

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

server.port=your_port

logging.level.org.hibernate.springframework=info
logging.level.root=info

logging.file.path=.